# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmDeletion_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfirmDeletion_Window(object):
    def setupUi(self, ConfirmDeletion_Window):
        ConfirmDeletion_Window.setObjectName("ConfirmDeletion_Window")
        ConfirmDeletion_Window.resize(220, 100)
        self.btn_yes = QtWidgets.QPushButton(ConfirmDeletion_Window)
        self.btn_yes.setGeometry(QtCore.QRect(10, 70, 100, 30))
        self.btn_yes.setObjectName("btn_yes")
        self.btn_no = QtWidgets.QPushButton(ConfirmDeletion_Window)
        self.btn_no.setGeometry(QtCore.QRect(110, 70, 100, 30))
        self.btn_no.setObjectName("btn_no")
        self.label = QtWidgets.QLabel(ConfirmDeletion_Window)
        self.label.setGeometry(QtCore.QRect(50, 20, 121, 31))
        self.label.setObjectName("label")

        self.retranslateUi(ConfirmDeletion_Window)
        QtCore.QMetaObject.connectSlotsByName(ConfirmDeletion_Window)

    def retranslateUi(self, ConfirmDeletion_Window):
        _translate = QtCore.QCoreApplication.translate
        ConfirmDeletion_Window.setWindowTitle(_translate("ConfirmDeletion_Window", "提示"))
        self.btn_yes.setText(_translate("ConfirmDeletion_Window", "是"))
        self.btn_no.setText(_translate("ConfirmDeletion_Window", "否"))
        self.label.setText(_translate("ConfirmDeletion_Window", "是否删除该邮件"))
