# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forwarding_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette,QBrush,QPixmap


class Ui_Forwarding_Window(object):
    def setupUi(self, Forwarding_Window):
        Forwarding_Window.setObjectName("Forwarding_Window")
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap(".\Background3.png")))
        Forwarding_Window.setPalette(palette)

        Forwarding_Window.resize(800, 600)
        self.label = QtWidgets.QLabel(Forwarding_Window)
        self.label.setGeometry(QtCore.QRect(10, 20, 72, 15))
        self.label.setObjectName("label")
        self.edt_receiver = QtWidgets.QLineEdit(Forwarding_Window)
        self.edt_receiver.setGeometry(QtCore.QRect(80, 15, 181, 20))
        self.edt_receiver.setObjectName("edt_receiver")
        self.label_2 = QtWidgets.QLabel(Forwarding_Window)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 72, 15))
        self.label_2.setObjectName("label_2")
        self.edt_theme = QtWidgets.QLineEdit(Forwarding_Window)
        self.edt_theme.setGeometry(QtCore.QRect(80, 64, 181, 21))
        self.edt_theme.setObjectName("edt_theme")
        self.label_3 = QtWidgets.QLabel(Forwarding_Window)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 72, 15))
        self.label_3.setObjectName("label_3")
        self.edt_text = QtWidgets.QTextEdit(Forwarding_Window)
        self.edt_text.setGeometry(QtCore.QRect(0, 150, 400, 400))
        self.edt_text.setObjectName("edt_text")
        self.label_4 = QtWidgets.QLabel(Forwarding_Window)
        self.label_4.setGeometry(QtCore.QRect(410, 120, 141, 16))
        self.label_4.setObjectName("label_4")
        self.edt_forwarding = QtWidgets.QTextEdit(Forwarding_Window)
        self.edt_forwarding.setGeometry(QtCore.QRect(400, 150, 400, 400))
        self.edt_forwarding.setObjectName("edt_forwarding")
        self.btn_forward = QtWidgets.QPushButton(Forwarding_Window)
        self.btn_forward.setGeometry(QtCore.QRect(350, 560, 100, 30))
        self.btn_forward.setObjectName("btn_forward")

        self.retranslateUi(Forwarding_Window)
        QtCore.QMetaObject.connectSlotsByName(Forwarding_Window)

    def retranslateUi(self, Forwarding_Window):
        _translate = QtCore.QCoreApplication.translate
        Forwarding_Window.setWindowTitle(_translate("Forwarding_Window", "转发"))
        self.label.setText(_translate("Forwarding_Window", "收件人："))
        self.label_2.setText(_translate("Forwarding_Window", "主题："))
        self.label_3.setText(_translate("Forwarding_Window", "正文："))
        self.label_4.setText(_translate("Forwarding_Window", "转发邮件信息："))
        self.btn_forward.setText(_translate("Forwarding_Window", "转发"))
