# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\APP_design\Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer,QDateTime


class Ui_Main_Window(object):

    def setupUi(self, Main_Window):
        Main_Window.setObjectName("Main_Window")
        Main_Window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_sendemail = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sendemail.setGeometry(QtCore.QRect(140, 170, 151, 41))
        self.btn_sendemail.setStyleSheet("backgroud:qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 235, 235, 206), stop:0.35 rgba(255, 188, 188, 80), stop:0.4 rgba(255, 162, 162, 80), stop:0.425 rgba(255, 132, 132, 156), stop:0.44 rgba(252, 128, 128, 80), stop:1 rgba(255, 255, 255, 0))")
        self.btn_sendemail.setObjectName("btn_sendemail")
        self.btn_receivebox = QtWidgets.QPushButton(self.centralwidget)
        self.btn_receivebox.setGeometry(QtCore.QRect(140, 270, 151, 41))
        self.btn_receivebox.setObjectName("btn_receivebox")
        self.btn_adressbook = QtWidgets.QPushButton(self.centralwidget)
        self.btn_adressbook.setGeometry(QtCore.QRect(140, 370, 151, 41))
        self.btn_adressbook.setObjectName("btn_adressbook")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, 0, 821, 561))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\Background2.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(290, 30, 200, 21))
        self.label_username.setStyleSheet("color:white;\n"
"\n"
"font-family: 微软雅黑;\n"
"\n"
"font-size:18px")
        self.label_username.setObjectName("label_username")
        self.label_2.raise_()
        self.btn_sendemail.raise_()
        self.btn_receivebox.raise_()
        self.btn_adressbook.raise_()
        self.label_username.raise_()
        Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Main_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main_Window)
        self.statusbar.setObjectName("statusbar")
        Main_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

        self.label_100 = QtWidgets.QLabel(Main_Window)
        self.label_100.setGeometry(QtCore.QRect(510, 0, 360, 41))  # label_100里面设置框的大小为左右510，上下0,宽360,高41
        self.Timer = QTimer()  # 自定义QTimer
        self.Timer.start(500)  # 每0.5秒运行一次
        self.Timer.timeout.connect(self.updateTime)  # 连接updateTime
        self.retranslateUi(Main_Window)
        QtCore.QMetaObject.connectSlotsByName(Main_Window)

    def updateTime(self):
            self.label_100.setText(QDateTime.currentDateTime().toString('yyyy-MM-dd hh:mm:ss dddd'))  # 显示时间的格式




    def retranslateUi(self, Main_Window):

        _translate = QtCore.QCoreApplication.translate
        Main_Window.setWindowTitle(_translate("Main_Window", "主界面"))
        self.btn_sendemail.setText(_translate("Main_Window", "发送邮件"))
        self.btn_receivebox.setText(_translate("Main_Window", "收件箱"))
        self.btn_adressbook.setText(_translate("Main_Window", "通讯录"))
        self.label_username.setText(_translate("Main_Window", "1"))
