# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SendEmail_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPalette,QBrush,QPixmap


class Ui_SendEmail_Window(object):
    def setupUi(self, SendEmail_Window):
        SendEmail_Window.setObjectName("SendEmail_Window")
        SendEmail_Window.resize(800, 600)
        palette = QPalette()
        palette.setBrush(QPalette.Background, QBrush(QPixmap(".\Background3.png")))
        SendEmail_Window.setPalette(palette)
        #SendEmail_Window.setStyleSheet("background-image:url(E:\python\APP_design\Background3.png)")

        self.centralwidget = QtWidgets.QWidget(SendEmail_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 72, 15))
        self.label_3.setObjectName("label_3")
        self.edt_MainText = QtWidgets.QTextEdit(self.centralwidget)
        self.edt_MainText.setGeometry(QtCore.QRect(60, 90, 701, 361))
        self.edt_MainText.setObjectName("edt_MainText")
        self.btn_Send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Send.setGeometry(QtCore.QRect(680, 520, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_Send.setFont(font)
        self.btn_Send.setObjectName("btn_Send")
        self.edt_Receiver = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_Receiver.setGeometry(QtCore.QRect(90, 10, 300, 21))
        self.edt_Receiver.setObjectName("edt_Receiver")
        self.edt_HeadLine = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_HeadLine.setGeometry(QtCore.QRect(90, 40, 300, 21))
        self.edt_HeadLine.setObjectName("edt_HeadLine")
        self.edt_Receiver_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.edt_Receiver_2.setGeometry(QtCore.QRect(390, 470, 391, 21))
        self.edt_Receiver_2.setObjectName("edt_Receiver_2")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(311, 470, 71, 20))
        self.label_4.setObjectName("label_4")

        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(50, 470, 106, 20))
        self.radioButton.setObjectName("radioButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 510, 200, 20))
        self.label_5.setObjectName("label_5")
        SendEmail_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SendEmail_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        SendEmail_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SendEmail_Window)
        self.statusbar.setObjectName("statusbar")
        SendEmail_Window.setStatusBar(self.statusbar)

        self.retranslateUi(SendEmail_Window)
        QtCore.QMetaObject.connectSlotsByName(SendEmail_Window)

    def retranslateUi(self, SendEmail_Window):
        _translate = QtCore.QCoreApplication.translate
        SendEmail_Window.setWindowTitle(_translate("SendEmail_Window", "MainWindow"))
        self.label.setText(_translate("SendEmail_Window", "收件人："))
        self.label_2.setText(_translate("SendEmail_Window", "标题："))
        self.label_3.setText(_translate("SendEmail_Window", "正文："))
        self.btn_Send.setText(_translate("SendEmail_Window", "发送"))
        self.label_4.setText(_translate("SendEmail_Window", "附件地址："))
        self.radioButton.setText(_translate("SendEmail_Window", "添加附件"))
        self.label_5.setText(_translate("SendEmail_Window", "欢迎使用本小组邮件管理系统"))
